### ISSUE TITLE
DashboardHelper.AddTab forces dashboard in "content" section

### ISSUE THREAD

**Issue by leekelleher** [agebase/umbraco-domain-manager#1]
The [`DashboardHelper.AddTab()`](https://github.com/agebase/umbraco-domain-manager/blob/master/source/AgeBase.DomainManager/Helpers/DashboardHelper.cs#L9) helper method forces the user to have the dashboard display in the "content" section.

I would like the dashboard to be movable to a different section.  For example, the "developer" section, so that associated domains/cultures are exposed to content-editors.

A proposed solution would be to have an `EnsureTab()` helper method, which would check if the dashboard-control's path is already in the `Dashboard.config`, with a fall-back on the default option (to add it in the "StartupDashboardSection" section).

I'm happy to provide a pull-request for this.

**Comment by danlister** [comment]
Thanks @leekelleher. The associated commit should fix the issue and allow developers to move the tab to other sections. I'll get this released in v1.0.1.

**Comment by leekelleher** [comment]
Cool, thanks @danlister!  That was quick! :-) (I wasn't meaning for you to do it straight away)

Don't rush on getting a new release out just yet, as it would be good to chat about #2 too.

Thanks again! #h5yr
