### ISSUE TITLE
Wildcard displayed for cultures set without hostname

### ISSUE THREAD

**Issue by leekelleher** [agebase/umbraco-domain-manager#2]
In the scenario where a culture is set against a node, but not a hostname, the following will be displayed...

![capture](https://cloud.githubusercontent.com/assets/209066/9197509/aacdbd3a-402c-11e5-8c37-6762b800f073.PNG)

This is due to Umbraco core internals prefixing the node's ID with an asterisks/wildcard.

What are your thoughts about displaying an alternative label for these?

**Comment by danlister** [comment]
I'm open to suggestions really. As the package is related to domains, I guess the list of domains should ignore any lone culture assignments. What do you think? I'm happy to go with any of your suggestions if you'd prefer it to display in a specific way.

**Comment by leekelleher** [comment]
I think it's good to have the cultures listed, but that's up to you if its beyond the scope of this package?

Maybe the Domain/hostname label could be a dash (unlinked)?

I'm not sure whether that should be done on the server-side or in angular?

**Comment by danlister** [comment]
Would something like the following be okay?

<img width="616" alt="screen shot 2015-08-11 at 14 41 27" src="https://cloud.githubusercontent.com/assets/596453/9198885/137d0250-4037-11e5-872b-ce55e8ecfb85.png">

**Comment by leekelleher** [comment]
Yeah, definitely! Looks good.

Thanks again for looking at this so quickly.
